
import { forwardRef } from "react";
import { AnalysisResult } from "@/lib/types";
import { StatsCard } from "./stats-card";
import { CalendarDays, Repeat, Wallet, Activity, User, Pencil } from "lucide-react";
import { Badge } from "./ui/badge";
import { Icons } from "./icons";
import { Timeline } from "./timeline";
import { Badges } from "./badges";
import { Separator } from "./ui/separator";

type PdfCardProps = {
  result: AnalysisResult;
  address: string;
};

export const PdfCard = forwardRef<HTMLDivElement, PdfCardProps>(
  ({ result, address }, ref) => {
    const { personalityData, stats, badges, timelineEvents } = result;
    const generationDate = new Date().toLocaleDateString();
    const truncatedAddress = `${address.substring(0, 10)}...${address.substring(address.length - 8)}`;

    return (
      <div
        ref={ref}
        className="fixed -left-[9999px] top-0 bg-background text-foreground p-10 font-body"
        style={{ colorScheme: "dark", width: 1200 }}
      >
        <div className="border rounded-lg p-10 space-y-8 h-full bg-card flex flex-col justify-between">
          <header className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Icons.logo className="h-10 w-10 text-primary" />
              <h1 className="text-2xl font-headline font-bold">
                Wallet Story Report
              </h1>
            </div>
            <div className="text-right">
                <p className="font-mono text-lg">{truncatedAddress}</p>
                <p className="text-sm text-muted-foreground">Generated on {generationDate}</p>
            </div>
          </header>

          <main className="flex-grow flex flex-col space-y-8">
            {/* Personality Title & Summary */}
            <div className="text-center space-y-3">
              <h2 className="text-4xl font-headline font-bold text-primary bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                {personalityData.personalityTitle}
              </h2>
              <p className="text-xl text-muted-foreground">
                {personalityData.oneLineSummary}
              </p>
            </div>

            {/* Traits */}
             <div className="bg-card border rounded-lg p-6 space-y-6">
                <div className="flex items-center gap-3">
                    <User className="h-5 w-5 text-primary" />
                    <h3 className="text-lg font-headline font-semibold">Personality Traits</h3>
                </div>
                <div className="flex flex-wrap gap-3">
                    {personalityData.traits.map((trait, index) => (
                        <Badge key={index} variant="secondary" className="text-base px-4 py-2">{trait}</Badge>
                    ))}
                </div>
            </div>

            {/* Story */}
            <div className="space-y-4">
                <div className="flex items-center gap-3">
                    <Pencil className="h-5 w-5 text-primary" />
                    <h3 className="text-lg font-headline font-semibold">Personality Story</h3>
                </div>
                <div className="prose prose-lg dark:prose-invert text-foreground/90 max-w-none">
                    <p className="whitespace-pre-wrap font-body" style={{lineHeight: 1.75}}>
                        {personalityData.personalityStory}
                    </p>
                </div>
            </div>

            {/* Achievements */}
            {badges && badges.length > 0 && (
                <>
                    <Separator />
                    <div className="space-y-6">
                        <h3 className="text-lg font-headline font-semibold text-center">Achievements ({badges.length})</h3>
                        <Badges badges={badges} />
                    </div>
                </>
            )}

            <Separator />
            
            {/* Stats */}
            <div className="grid grid-cols-2 gap-4">
              <StatsCard title="Wallet Age" value={`${stats.walletAge} days`} icon={CalendarDays} />
              <StatsCard title="Transactions" value={stats.txCount} icon={Repeat} />
              <StatsCard title="ETH Balance" value={`${stats.balance} ETH`} icon={Wallet} />
              <StatsCard title="Activity" value={stats.activityStatus} icon={Activity} />
            </div>

            {/* Timeline */}
            {timelineEvents && timelineEvents.length > 0 && (
                <>
                    <Separator />
                    <div className="space-y-6">
                        <h3 className="text-lg font-headline font-semibold text-center">Wallet Journey</h3>
                        <Timeline events={timelineEvents} />
                    </div>
                </>
            )}

          </main>
          
          <footer className="text-center text-sm text-muted-foreground pt-8">
            <p>
              Generated by{" "}
              <span className="text-primary">
                wallet-summary.vercel.app
              </span>
            </p>
          </footer>
        </div>
      </div>
    );
  }
);

PdfCard.displayName = "PdfCard";
