
import { forwardRef } from "react";
import { AnalysisResult, ImageFormat } from "@/lib/types";
import { StatsCard } from "./stats-card";
import { CalendarDays, Repeat, Wallet, Activity } from "lucide-react";
import { Badge } from "./ui/badge";
import { Icons } from "./icons";
import { cn } from "@/lib/utils";

type ShareCardProps = {
  result: AnalysisResult;
  address: string;
  format: ImageFormat;
  dimensions: { width: number; height: number };
};

export const ShareCard = forwardRef<HTMLDivElement, ShareCardProps>(
  ({ result, address, format, dimensions }, ref) => {
    const { personalityData, stats } = result;
    const truncatedAddress = `${address.substring(0, 6)}...${address.substring(address.length - 4)}`;
    const storyExcerpt = personalityData.personalityStory.split('. ').slice(0, 2).join('. ') + '.';

    const isStory = format === 'Story';

    return (
      <div
        ref={ref}
        className="fixed -left-[9999px] top-0 bg-background text-foreground font-body"
        style={{ colorScheme: "dark", width: dimensions.width, height: dimensions.height }}
      >
        <div className={cn(
          "border rounded-lg p-10 space-y-6 h-full bg-card flex flex-col justify-between",
           isStory ? "p-8 space-y-8" : "p-10 space-y-6"
        )}>
          <header className="flex items-start justify-between">
            <div className="flex items-center gap-4">
              <Icons.logo className={cn("text-primary", isStory ? "h-8 w-8" : "h-10 w-10")} />
              <h1 className={cn("font-headline font-bold", isStory ? "text-xl" : "text-2xl")}>
                Wallet Story Explorer
              </h1>
            </div>
            <div className="text-right flex-shrink-0">
                <p className={cn("font-mono", isStory ? "text-base" : "text-lg")}>{truncatedAddress}</p>
                <p className="text-sm text-muted-foreground">Wallet Address</p>
            </div>
          </header>

          <main className={cn(
            "flex-grow flex flex-col justify-center",
            isStory ? "space-y-6" : "space-y-8"
            )}>
            <div className="text-center space-y-3">
              <h2 className={cn(
                "font-headline font-bold text-primary bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent",
                isStory ? "text-5xl" : "text-6xl"
                )}>
                {personalityData.personalityTitle}
              </h2>
              <p className={cn("text-muted-foreground", isStory ? "text-lg" : "text-xl")}>
                {personalityData.oneLineSummary}
              </p>
            </div>

            <div className="flex justify-center flex-wrap gap-3">
              {personalityData.traits.map((trait, index) => (
                <Badge
                  key={index}
                  variant="secondary"
                  className={cn(isStory ? "text-base px-4 py-2" : "text-lg px-6 py-3")}
                >
                  {trait}
                </Badge>
              ))}
            </div>

            <div className={cn("text-center text-foreground/90 max-w-2xl mx-auto", isStory ? "text-base" : "text-lg")} style={{ lineHeight: 1.6 }}>
              <p>{storyExcerpt}</p>
            </div>
          </main>
          
          <div className={cn("grid gap-4", isStory ? "grid-cols-2" : "grid-cols-4")}>
            <StatsCard title="Wallet Age" value={`${stats.walletAge}d`} icon={CalendarDays} />
            <StatsCard title="Transactions" value={stats.txCount} icon={Repeat} />
            <StatsCard title="ETH Balance" value={`${parseFloat(stats.balance).toFixed(2)}`} icon={Wallet} />
            <StatsCard title="Activity" value={stats.activityStatus} icon={Activity} />
          </div>


          <footer className="text-center text-sm text-muted-foreground pt-4">
            <p>
              Generated by{" "}
              <span className="text-primary">
                wallet-summary.vercel.app
              </span>
            </p>
          </footer>
        </div>
      </div>
    );
  }
);

ShareCard.displayName = "ShareCard";
